version: '3.1'
services:
  minecraft:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        VERSION: "1.16.3"
    volumes:
      - ./server/:/home/
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
    user: "${SUDO_UID}:${SUDO_GID}"
    ports:
      - "25565:25565"
    environment:
      - "Xms=2g"
      - "Xmx=4g"
    stdin_open: true
    tty: true

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./server/mods:/pub/mods:ro
      - ./server/config:/pub/config:ro
    ports:
      - "8081:8080"
