version: '3.1'
services:
  minecraft:
    build:
      context: .
      args:
        VERSION: "forge-1.17.1" # 1.16.5, forge-1.12.2, fabric-1.17.1
    volumes:
      - ./server/:/home/
    user: "nobody:nogroup" # Uncomment if windows
    ports:
      - "25565:25565"
    environment:
      Xms: "6g" # memory min
      Xmx: "12g" # memory max
      eula: "true" # !!!EDIT ("true")!!!
    stdin_open: true
    tty: true
    restart: unless-stopped

  nginx:
    build:
      context: nginx
      dockerfile: Dockerfile
    volumes:
      - ./server/:/data/:ro
    ports:
      - "8080:8080"
